basic dotnet setup (#9)
* basic setup

* add files

* update gitignore

* add basic page and section models

* wip

* Make sections work

* remove strapi

* frontend stuff

* add page mappers

* WIP add ServicesSection

* WIP (#10)

* WIP

* fix new page implementation

* move .net project to root

---------

Co-authored-by: Jonas Faber <jonas@hagenfaber.eu>
Co-authored-by: Jonas Faber <jonas.h.faber@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,4 +23,15 @@ jobs:
         run: npm run build --prefix frontend
 
       - name: Test build output exists
-        run: test -d dist && echo "Build successful" || echo "Build failed"
+        run: test -d frontend/dist && echo "Build successful" || echo "Build failed"
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: 9.0.x
+      - name: Restore dependencies
+        run: dotnet restore
+      - name: Build
+        run: dotnet build --no-restore
+      - name: Test
+        run: dotnet test --no-build --verbosity normal
